export type Technology =
    | "AWS"
    | "Bluetooth"
    | "Bootstrap"
    | "C"
    | "C++"
    | "C#"
    | "Docker"
    | "Express"
    | "Flask"
    | "GraphQL"
    | "HTML"
    | "Java"
    | "JavaScript"
    | "Jest"
    | "Markdown"
    | "MATLAB"
    | "Mixpanel"
    | "Mongodb"
    | "Next"
    | "Nginx"
    | "Node"
    | "Oracle"
    | "Python"
    | "Rancher"
    | "Raspberry Pi"
    | "React"
    | "SCSS"
    | "Sentry"
    | "SQL"
    | "SQL Server"
    | "Swift"
    | "Tailwind"
    | "Terraform"
    | "Three"
    | "TypeScript"
    | "Microsoft.NET";